# File: ielts-scorer/docker-compose.yml
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
      - ./ielts_scorer.db:/app/ielts_scorer.db
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis

  worker:
    build: .
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
      - ./ielts_scorer.db:/app/ielts_scorer.db
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
    command: celery -A app.celery_app worker --loglevel=info --pool=solo
    depends_on:
      - redis